### ISSUE TITLE
Ejercicios 5 y 6 del tema de Gestión de configuraciones son similares

### ISSUE THREAD

**Issue by Griger** [JJ/CC#11]
[El documento](https://github.com/JJ/CC/blob/master/documentos/temas/Gestion_de_configuraciones.md)
[El documento en github pages](http://jj.github.io/CC/documentos/temas/Gestion_de_configuraciones)

**Comment by JJ** [comment]
Gracias. Lo miro.

**Comment by JJ** [comment]
Este fichero fue eliminado en 166822de50ed922c0fd3d8ef7e984bbbad7f2368. Vamos a ver si hay el mismo problema en el siguiente.
