### ISSUE TITLE
Ampliación apuntes provisionamiento ligero

### ISSUE THREAD

**Issue by Griger** [JJ/CC#12]
**Aquí un pequeño resumen del proceso seguido para levantar el primer contenedor LXC:**

Tras instalar LXC en Arch junto con el paquete *arch-install-scripts* (que sugiere en la documentación de Arch que se instale) con los comandos:

```bash
pacaur -S lxc
pacaur -S arch-install-scripts
```

Lo primero que observamos es que, como dice en la documentación anteriormente nelazada, los namespaces de usuario no aparecen como disponibles cuando comprobamos con `lxc-checkconfig`, esto es aparentemente por un motivo de seguridad de Arch lo que nos obliga a ejecutar los comandos con sudo al parecer.

Una vez hecho esto al intentar crear una máquina con Ubuntu con el comando `sudo lxc-create -t ubuntu -n una-caja` nos daba un error indicando que no podía ejecutar el comando debootstrap, con lo que lo hemos instalado por medio del comando `sudo pacman -S debootstrap`.

Una vez hecho esto, y tras un tiempo de espera, se ha configurado un contenedor con Ubuntu que arrancamos son `sudo lxc-start -n una-caja` y a la que nos ponemos conectar con `sudo lxc-console -n una caja`. Al hacer esto antes de pulsar ENTER que nos iniciará la consola de dicho contenedor, hemos de fijarno que cuando queramos salir de dicha consola hemos de emplear `Ctrl+a q`, si empleamos el comando `exit` lo único que haremos será "salir" de la máquina y aparecerá de nuevo la petición de usuario y contraseña para volver a entrar en ella.

**Comment by JJ** [comment]
Esta parte realmente se ha eliminado de los apuntes, pero se podría añadir a la documentación adicional. Gracias.
