### ISSUE TITLE
Modularizar enlaces y referencias

### ISSUE THREAD

**Issue by alejnp** [JJ/CC#31]
Como este repositorio es un trabajo evolutivo en tiempo (cada curso escolar), recomendaría adaptar los enlaces de los archivos `Markdown` de "enlace inmediato" a "enlace referenciado", es decir:

```plain
# "Enlace inmediato"
Los criterios generales que figuran en la [guía docente](***) son los siguientes

# "Enlace referenciado"
Los criterios generales que figuran en la [guía docente][***] son los siguientes
···
···
[guia-docente]: ***
```

Esto permitiría definir los enlaces en un lugar más apropiado, como sea el final de la sección o capítulo, así como más fácil mantenerlos actualizados.

Para más información, consulta [la documentación de CommonMark](https://spec.commonmark.org/0.29/#links), un intento de estandarizar `Markdown`.

**Comment by JJ** [comment]
Pero ¿GitHub sigue ese estándar?

**Comment by JJ** [comment]
No estoy seguro que haya enlaces que se repitan, también... Sí puede haberlos en otros temas que no son exactamente con fecha, sino simplemente muchas referencias al mismo sitio.

**Comment by Alxe** [comment]
> Pero ¿GitHub sigue ese estándar?

Es algo más complejo que eso, CommonMark sigue el "flavour" de GitHub (además de otros) y procura estandarizarlo de forma que exista una referencia bien explícita para desarrollar herramientas que entiendan `Markdown`.

> No estoy seguro que haya enlaces que se repitan, también... Sí puede haberlos en otros temas que no son exactamente con fecha, sino simplemente muchas referencias al mismo sitio.

Indiferentemente de si se repite o no, si usases "link labels" podrías estructurar mejor el documento, facilitando la lectura a la hora de verlo en texto plano. Como bonus adicional, es que puedas usar la misma referencia en varios enlaces.

**Comment by JJ** [comment]
OK. Si te animas, los PRs siguen abiertos :-)
